### ISSUE TITLE
Investigate instance type optimization

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/deploy-logs-opensearch#143]
Based on whether a VM is CPU-bound or memory-bound, it may make sense to switch to a different EC2 instance type to improve performance.

## To do

- [ ] View metrics for VM performance in production
- [ ] Evaluate whether instances would benefit from memory, CPU, or both
- [ ] Adjust instance types in deployment configuration as necessary

**Comment by JasonTheMain** [comment]
Upping instance type won't save money and will have same effeciency
