### ISSUE TITLE
Add staging deployment

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/deploy-logs-opensearch#45]
## To do

- [ ] Update pipeline and manifest/opsfiles as necessary to deploy logs OpenSearch in staging

## Acceptance Criteria

- [ ] OpenSearch deployment is accessible and functional in staging

**Comment by JasonTheMain** [comment]
Credhub variables up to manifest exist

**Comment by JasonTheMain** [comment]
waiting on #1044

**Comment by markdboyd** [comment]
OpenSearch is running and available in staging
