### ISSUE TITLE
Add production deployment

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/deploy-logs-opensearch#46]
## To do

- [ ] Update pipeline and manifest/opsfiles as necessary to deploy logs OpenSearch in production

## Acceptance Criteria

- [ ] OpenSearch deployment is accessible and functional in production
- [ ] Explore how to monitor/test the ideal performance based on guidance from Elastic or Opensearch (shard/size ratio, etc)

**Comment by JasonTheMain** [comment]
Production is ready for test deploying in production, currently under the assumption all variables and values are set as needed for this until we can run test deploy in production

**Comment by markdboyd** [comment]
Superseded by https://github.com/cloud-gov/private/issues/2004
